version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pia_postgres
    restart: always
    environment:
      POSTGRES_USER: pia_user
      POSTGRES_PASSWORD: pia_password
      POSTGRES_DB: pia_manager
    ports:
      - "5432:5432"
    volumes:
      - pia_db_data:/var/lib/postgresql/data

volumes:
  pia_db_data: